### ISSUE TITLE
Implement external config file

### ISSUE THREAD

**Issue by sebastianknopf** [sebastianknopf/gtfs-incident-alerts#1]
The module should be configurable similar to all other modules using an external YAML config file. If no config file is specified, a default config should be used internally.

The configuration is esoecially used for indicating whether file output or MQTT should be used, and also which output formst should be used.

**Comment by sebastianknopf** [comment]
Following configs should be implemented in this issue:

```yaml
app:
  mqtt_enabled: false
mqtt:
  host: test.mosquitto.org
  port: 1883
  client: gtfs-incident-alerts
  keepalive: 60
  username: null
  password: null
  service_alerts_topic: realtime/sample/service-alerts/[alertId]
```
